#!/usr/bin/env python3
import os
import subprocess
import sys
import time
from pathlib import Path


def c_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def git_text(root: Path, args, fallback: str) -> str:
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=root,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
        )
        return result.stdout.strip() or fallback
    except (OSError, subprocess.CalledProcessError):
        return fallback


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: generate_build_info.py OUT ROOT_DIR", file=sys.stderr)
        return 2

    out_path = Path(sys.argv[1])
    root = Path(sys.argv[2])
    epoch = int(os.environ.get("SOURCE_DATE_EPOCH", str(int(time.time()))))
    build_time = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(epoch))
    git_sha = git_text(root, ["rev-parse", "--short=12", "HEAD"], "unknown")
    dirty = git_text(root, ["status", "--short"], "")
    build_id = f"{git_sha}{'-dirty' if dirty else ''}+{epoch}"

    lines = [
        "#pragma once",
        "",
        "/* Generated by scripts/tools/generate_build_info.py. Do not edit directly. */",
        "",
        f"#define APP_BUILD_ID {c_string(build_id)}",
        f"#define APP_BUILD_GIT_SHA {c_string(git_sha)}",
        f"#define APP_BUILD_DIRTY {1 if dirty else 0}",
        f"#define APP_BUILD_TIME_UTC {c_string(build_time)}",
        f"#define APP_BUILD_EPOCH {epoch}",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
